"""Change email attachment storage to URL

Revision ID: 980e54b5c7ff
Revises: efb17718b8b7
Create Date: 2025-07-12 12:45:44.142151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980e54b5c7ff'
down_revision: Union[str, Sequence[str], None] = 'efb17718b8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_email_logs', sa.Column('attachment_filename', sa.String(), nullable=True))
    op.add_column('raw_email_logs', sa.Column('attachment_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_email_logs', 'attachment_url')
    op.drop_column('raw_email_logs', 'attachment_filename')
    # ### end Alembic commands ###
