"""Change raw_email_logs recipients to JSON type

Revision ID: c13a59bf3a18
Revises: 4a95c2d9dbaf
Create Date: 2025-07-11 19:35:41.776118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13a59bf3a18'
down_revision: Union[str, Sequence[str], None] = '4a95c2d9dbaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_email_logs', 'recipients',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="CASE WHEN recipients IS NULL THEN '[]'::json ELSE to_json(ARRAY[recipients]) END")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_email_logs', 'recipients',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
